# Generated by Django 4.2.7 on 2023-11-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_padariaDJ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
